# Generated by Django 3.2.9 on 2022-03-28 05:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tours.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartingDate', models.DateField()),
                ('FinishingDate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Departures',
                'ordering': ('-tour', 'DepartingDate'),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Pamir', max_length=100, verbose_name='Destination title')),
                ('Slug', models.SlugField(blank=True, default='', help_text='Do not change it!', max_length=100, unique=True, verbose_name='Slug')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Введите контент', null=True, verbose_name='Content')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='destinations/')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Sorting Index')),
                ('pageid', models.IntegerField(blank=True, default=1, help_text='This value is used in views.py', verbose_name='Page id')),
                ('start_price', models.IntegerField(blank=True, default=99, help_text='Starting price in the destination', verbose_name='Starting Price')),
                ('seo_title', models.CharField(blank=True, default='', help_text='Enter the Title. Max: 60 characters', max_length=60, null=True, verbose_name='SEO Title')),
                ('seo_content', models.TextField(blank=True, default='', help_text='Enter the content. Max: 165 characters', max_length=165, null=True, verbose_name='SEO Content')),
                ('seo_keywords', models.TextField(blank=True, default='', help_text='Enter keywords, max 200 symbols', max_length=200, null=True, verbose_name='SEO Keywords')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photogalleries/galleries/')),
                ('description', models.CharField(blank=True, help_text='Enter the description of the album.', max_length=300, verbose_name='Description')),
                ('published', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TourActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=50, verbose_name='Activity')),
                ('Slug', models.SlugField(blank=True, default='', help_text='Do not change it!', max_length=100, verbose_name='Slug')),
                ('sortingIndex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TourTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=100)),
                ('Slug', models.SlugField(blank=True, default='', help_text='Do not change it!', max_length=100)),
                ('sortingIndex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAvailability',
            fields=[
                ('departures', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='departure_place_availability', serialize=False, to='tours.departures')),
                ('BookedPlaces', models.IntegerField(blank=True, verbose_name='Booked places')),
                ('AvailablePlaces', models.IntegerField(blank=True, verbose_name='Available Places')),
                ('TotalPlaces', models.IntegerField(blank=True, verbose_name='Total Places')),
            ],
            options={
                'verbose_name_plural': 'Place Availability',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TourCode', models.CharField(help_text='Ex. JT001 ', max_length=10, unique=True)),
                ('Title', models.CharField(help_text='Title of the tour here', max_length=200)),
                ('Slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('TourType', models.CharField(blank=True, choices=[('jeep-tours', 'Jeep Tours'), ('cultural-tours', 'Cultural Tours'), ('trekking-and-hiking', 'Trekking & Hiking'), ('cycling-tours', 'Cycling Tours'), ('city-tours', 'City Tours'), ('wildlife-tours', 'Wildlife Tours')], help_text='Check any that applies to your tour', max_length=20, null=True, verbose_name='Tour Type')),
                ('Duration', models.IntegerField(default=0)),
                ('ShortDesc', models.TextField(blank=True, default='', help_text='Short description', max_length=165, verbose_name='Short Description')),
                ('Description', models.TextField(help_text='Description of the tour...')),
                ('Inclusions', models.TextField(help_text='Inclusions of the tour')),
                ('Exclusions', models.TextField(help_text='Exclusions of the tour; Seperate them with semicolon')),
                ('Difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, help_text='Enter a value between 1 to 10')),
                ('GroupSize', models.CharField(blank=True, help_text='Group size', max_length=2, verbose_name='Group size')),
                ('Seasonality', models.CharField(help_text='Seasonality of the tour; Ex. July - September', max_length=100)),
                ('Highlights', models.TextField(help_text='Highlights of the tour. Seperate with semicolon. Ex. Yamchun fortress; etc')),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PriceList', models.TextField(blank=True, help_text='Price List')),
                ('Image', imagekit.models.fields.ProcessedImageField(upload_to='tours/main-image/%Y/%m/%d/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Available', models.BooleanField(default=True)),
                ('Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('Route', models.CharField(blank=True, help_text='Route. Example: Dushanbe - Murghab- Osh', max_length=400)),
                ('ImportantNotes', models.TextField(blank=True, help_text='Seperate the important notes with semicolons.', verbose_name='Important Notes')),
                ('NumberOfDays', models.IntegerField(default=5, help_text='Enter the number of days', verbose_name='Number Of Days')),
                ('NumberOfNights', models.IntegerField(default=5, help_text='Enter the number of nights', verbose_name='Number Of Nights')),
                ('StartingPoint', models.CharField(default='Dushanbe', help_text='Starting point. Ex. Dushanbe, Tajikistan', max_length=50, verbose_name='Starting Point')),
                ('EndingPoint', models.CharField(default='Dushanbe', help_text='Ending point. Ex. Dushanbe, Tajikistan', max_length=50, verbose_name='Ending Point')),
                ('Approved_tour', models.BooleanField(default=False)),
                ('Deposit', models.FloatField(blank=True, default=0.0, help_text='Enter deposit. Ex. 100')),
                ('adminNotes', models.TextField(blank=True, default='', help_text="This field is just for admin. Users don't see it", verbose_name='Admin Notes')),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('sortingIndex', models.IntegerField(default=0)),
                ('Destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.destination')),
                ('Gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.gallery')),
            ],
            options={
                'ordering': ('sortingIndex', '-Created'),
                'index_together': {('id', 'Slug')},
            },
        ),
        migrations.CreateModel(
            name='TaggedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_taggedtour_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Example: Day 01: Arrival in Dushanbe ', max_length=200, verbose_name='Itinerary Title')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='tours/itineraries/%Y/%m/%d/')),
                ('Description', models.TextField(help_text='Description of the day', verbose_name='Itinerary Description')),
                ('orderingIndex', models.IntegerField(default=0, help_text='Used for ordering teh image in the album from smaller to bigger digit')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_itineraries', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='departures',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_departures', to='tours.tour'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=tours.models.get_path)),
                ('caption', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('orderingIndex', models.IntegerField(default=0, help_text='Used for ordering teh image in the album from smaller to bigger digit')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.gallery')),
            ],
            options={
                'ordering': ('orderingIndex', 'created'),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
