# Generated by Django 3.2.9 on 2022-03-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220328_1051'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='seo_content',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='destination',
            name='SEO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seo_optimiser'),
        ),
        migrations.AddField(
            model_name='destination',
            name='ShortDesc',
            field=models.TextField(blank=True, help_text='Used on photos ', max_length=165, null=True, verbose_name='Short Desciption'),
        ),
    ]
