# Generated by Django 3.2.9 on 2022-03-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20220328_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='pageid',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Deposit',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Difficulty',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='adminNotes',
        ),
    ]
