# Generated by Django 3.2.9 on 2022-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20220328_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departures',
            name='DepartingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departures',
            name='FinishingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
