# Generated by Django 3.2.9 on 2022-04-19 16:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20220330_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Long description of the tour...', null=True, verbose_name='Description'),
        ),
    ]
