# Generated by Django 3.1.7 on 2021-03-05 10:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Enter the title of the post.', max_length=300, verbose_name='Post Title')),
                ('Slug', models.SlugField(blank=True, help_text='Slug is what is seen in the URL. Ex. this-is-a-post', max_length=300, unique=True)),
                ('ShortDesc', models.TextField(blank=True, help_text='Enter the short description of the post here', verbose_name='Short Description')),
                ('Content', ckeditor.fields.RichTextField(help_text='Enter the post content', verbose_name='Post content')),
                ('posttype', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('Image', imagekit.models.fields.ProcessedImageField(upload_to='blog/%Y/%m/%d/')),
                ('VideoEmbedCode', models.TextField(blank=True, help_text='Enter the Video Embed Code here', verbose_name='Video Embed Code')),
                ('published', models.DateTimeField(auto_now=True)),
                ('allow_commenting', models.BooleanField(default=True)),
                ('hide_comments', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Created',),
            },
        ),
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_taggedpost_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='blog.TaggedPost', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('id', 'Slug')},
        ),
    ]
