# Generated by Django 3.2.9 on 2022-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211116_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pageid',
            field=models.IntegerField(blank=True, default=1, help_text='This value is used in views.py', verbose_name='Page id'),
        ),
        migrations.AlterField(
            model_name='seo_optimiser',
            name='seoid',
            field=models.IntegerField(blank=True, default=0, help_text='This text is used in views.py', null=True, unique=True, verbose_name='SEO id'),
        ),
    ]
