# Generated by Django 3.2.9 on 2022-03-24 13:48

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220316_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, default='', help_text='Enter the Title. Max: 60 characters', max_length=60, null=True, verbose_name="Client's name and surname")),
                ('Content', models.TextField(blank=True, default='', help_text='Enter the content. Max: 165 characters', max_length=165, null=True, verbose_name='Content')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='feedbacks/%Y/')),
                ('ProductTook', models.CharField(blank=True, default='Pamir Highway Tour', max_length=55, null=True, verbose_name='Product Took')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
