# Generated by Django 3.2.9 on 2022-03-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalsAndServices',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.page')),
                ('Slug', models.CharField(blank=True, help_text='Enter the link. Ex.: eto-publikaciya', max_length=100, null=True, unique=True)),
                ('ShortDesc', models.TextField(blank=True, help_text='Enter the short description of the page using 165 symbols', max_length=165, null=True, verbose_name='Short Desciption')),
            ],
            options={
                'verbose_name': 'Rentals and Services',
                'verbose_name_plural': 'Rentals and Services',
            },
            bases=('home.page',),
        ),
    ]
