# Generated by Django 3.2.9 on 2022-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rentalsandservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='SEO',
        ),
        migrations.AddField(
            model_name='page',
            name='seo_content',
            field=models.TextField(blank=True, default='', help_text='Enter the content. Max: 165 characters', max_length=165, null=True, verbose_name='SEO Content'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', help_text='Enter keywords, max 200 symbols', max_length=200, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Enter the Title. Max: 60 characters', max_length=60, null=True, verbose_name='SEO Title'),
        ),
    ]
