# Generated by Django 3.2.9 on 2022-03-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220328_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='seo_content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='page',
            name='SEO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seo_optimiser'),
        ),
    ]
